//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankService.DataBaseInteraction
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banknote
    {
        public int Denomination { get; set; }
        public long Quantity { get; set; }
    }
}
